schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.97.0"
    hash = "sha256-PZ2iRkfQkTDC4zIwUS46zC2xkj1YDgWTnzswrvrlFvs="
  [mod."github.com/Azure/go-autorest"]
    version = "v14.2.0+incompatible"
    hash = "sha256-dvWOcudtx0NP6U2RDt40hwtELFRdYdLEklRWYterRN0="
  [mod."github.com/Azure/go-autorest/autorest"]
    version = "v0.11.27"
    hash = "sha256-GyC325XaMvXJswcrJxVe89dsHJ0l/XIoIA9/fzUZF2Y="
  [mod."github.com/Azure/go-autorest/autorest/adal"]
    version = "v0.9.20"
    hash = "sha256-8G4AGv+/o0lbdhS32Cd2YAykD40PoNJaxydxzOCE5S0="
  [mod."github.com/Azure/go-autorest/autorest/date"]
    version = "v0.3.0"
    hash = "sha256-PWFHUZ9jMJ6gkMCnRpR89s/aI3YdtzskIePj8Ulu4dc="
  [mod."github.com/Azure/go-autorest/logger"]
    version = "v0.2.1"
    hash = "sha256-xGqpcF7fL1MQCN4xXTHpAFDzEA5f4p6kdb9yV1+uB4k="
  [mod."github.com/Azure/go-autorest/tracing"]
    version = "v0.6.0"
    hash = "sha256-CcLYoOyRcMo4aRRYN+TBbaHtJqDra4e0qo3cmGZIB74="
  [mod."github.com/PuerkitoBio/purell"]
    version = "v1.1.1"
    hash = "sha256-Hjf8ZNNdwcRd50A9QNrcCj17gu/6f1iKzVTVrrMrojA="
  [mod."github.com/PuerkitoBio/urlesc"]
    version = "v0.0.0-20170810143723-de5bf2ad4578"
    hash = "sha256-nL0/0QM0Pec83vBlwXvQ8g5SvvZnCQgzD1apxfHNGlg="
  [mod."github.com/aws/aws-sdk-go"]
    version = "v1.44.235"
    hash = "sha256-jg8Edsm1/y0TW3rPmRYNxSJZfIAI4zmj+43JcbneBJk="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.15.0"
    hash = "sha256-DyphnjmsV0+sXdhXcjP/4t5pKqDFokKyqEcMCnK1mTw="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v0.23.2"
    hash = "sha256-ZIjkMtD5izq+8h5F6Po3FER28hS5Rh1hJsKozoinMX8="
  [mod."github.com/charmbracelet/harmonica"]
    version = "v0.2.0"
    hash = "sha256-fi5N0IXhSbbYHdSZFngCfpT4kdiEaKedqj8YpnlvX0o="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v0.7.1"
    hash = "sha256-GdPbyi762tGmU0ASLv76/DDjOubYp6K1kNio/IUVUiQ="
  [mod."github.com/containerd/console"]
    version = "v1.0.3"
    hash = "sha256-4p4u/rS7G4KKbIcZaVMqE1OtSoNlOpmcYFwO0ZEH/V0="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.8.0"
    hash = "sha256-VIy44CDcwVVHsUobY/LxdN/JcV5RcZS74s2q9xIxkSw="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.3"
    hash = "sha256-2L7k6GfrcW3GXXYr1FYIu20aZBjIF0cTKdte6D4riH8="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.5"
    hash = "sha256-rLyvUdTMeQGeWiVsz2ZeyyFjHomeqd0x+ZR77mxi8Ss="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.19.5"
    hash = "sha256-EMbFFOrhvKFVmJ2vierWGCmDy1Vl08HBgUBd9xw2cD8="
  [mod."github.com/go-openapi/swag"]
    version = "v0.19.14"
    hash = "sha256-MRuOz461M5BHBAGYJdhBA8vP682EocgvgGQxpXxhJbo="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.2.0"
    hash = "sha256-ajcJIgh/0LGlCmgAUlXNgJW8u9uuiMBhnUwWq9uS4X8="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/google/gnostic"]
    version = "v0.5.7-v3refs"
    hash = "sha256-faR3RiaCBLgZsG1H5KRimlyOu4Grv1ENlYn3f7OAzhU="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.6"
    hash = "sha256-OlzzRmcIdX45NA5h/C90NfJ/th0LB+tMHT6WzdQFK1M="
  [mod."github.com/google/gofuzz"]
    version = "v1.1.0"
    hash = "sha256-PSNufXo20YXfSNbayCc3hdujKZT5EW4lybsQ+WJ0Imo="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.6"
    hash = "sha256-B4uSmAVWme2nDAqbW9XiwlEnCg7CAvewToNsji7yf9E="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.6"
    hash = "sha256-lObieB06Ep7xL3Bbc1sxWpAeqH9VH2LXsPIc9uueuXs="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.17"
    hash = "sha256-c1u9eiMF9wLXgGvPTB5DH6S8uuCPqWZJTa6tCGuB3Ek="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.2-0.20220822084749-2491eb6c1c75"
    hash = "sha256-6XnWsrip4a46ywpFNrfbhY7usbFxWySD1lDMF3SygJU="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.14"
    hash = "sha256-O3QdxqAcJgQ+HL1v8oBA4iKBwJ2AlDN+F464027hWMU="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20211018074035-2e021307bc4b"
    hash = "sha256-v4zQmLl5Z6hoKtuH0Ry6hRwAKNWna4rXirK62LXNvbY="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.15.1"
    hash = "sha256-vbltynBfzDXd+XO/naRmAeh71o8jlT7Y4fHA1Jj6qg8="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/rivo/uniseg"]
    version = "v0.2.0"
    hash = "sha256-GLj0jiGrT03Ept4V6FXCN1yeZ/b6PpS3MEXK6rYQ8Eg="
  [mod."github.com/samber/lo"]
    version = "v1.38.1"
    hash = "sha256-P0awJtu/YJIG+jrSrttBCIIf+JTn4y1VZvgJAR9nncY="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20220315160706-3147a52a75dd"
    hash = "sha256-I4+PX0w35ajTGYWilmBkkXj37I+mBXYHggB5uJzL/T0="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20220303212507-bbda1eaf7a17"
    hash = "sha256-E8mRbh+ptVwyqnxBfYEtJ8pGqjWUvxUxVsz9vXxDIo4="
  [mod."golang.org/x/net"]
    version = "v0.7.0"
    hash = "sha256-LgZYZRwtMqm+soNh+esxDSeRuIDxRGb9OEfYaFJHCDI="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20211104180415-d3ed0bb246c8"
    hash = "sha256-mE99ygMLxlbLazt3kqIteXAFnS05EHVE14CyOFPfk+8="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.6.0"
    hash = "sha256-zAgxiTuL24sGhbXrna9R1UYqLQh46ldztpumOScmduY="
  [mod."golang.org/x/term"]
    version = "v0.5.0"
    hash = "sha256-f3DiX7NkDsEZpPS+PbmnOH9F5WHFZ1sQrfFg/T2UPno="
  [mod."golang.org/x/text"]
    version = "v0.7.0"
    hash = "sha256-ydgUqX+t5Qke16C6d3FP/06U/N1n+rUKpLRFj4KXjwk="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20220210224613-90d013bbcef8"
    hash = "sha256-pg5k2aqln5KoTOK/vya61T7DALmcs0CFVH9MPUj62v0="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.0"
    hash = "sha256-p1cVM3OeEErh1WeNRAg4n3zYm/0qPTPmIiWNjRmJiMQ="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."k8s.io/api"]
    version = "v0.25.0"
    hash = "sha256-I47NPRYhksbpSbPgJmG7e1/zFNZf+whEatGsXpikQYg="
  [mod."k8s.io/apimachinery"]
    version = "v0.25.0"
    hash = "sha256-EBEUxqoiHVk6dwyPj0q/3ChLwZGTlLYtYn9Ayw4zpvo="
  [mod."k8s.io/client-go"]
    version = "v0.25.0"
    hash = "sha256-q1NNxo77p1u3ThCJ7s5jj6Yj7dpDex1nYubV2ECKXM0="
  [mod."k8s.io/klog/v2"]
    version = "v2.70.1"
    hash = "sha256-5T+X0tyldk6/qlbqOSCc2ekGv48RmcgLQcR9aKrWi5U="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20220803162953-67bda5d908f1"
    hash = "sha256-R/Ijb3dmKxlUQLPOka7giQNxQIIFFLK6FkuCqXFI2Yk="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20220728103510-ee6ede2d64ed"
    hash = "sha256-VQdAHhGRzEEqjljwqVjZB/6o44L3MJ7V7kk5fh+Ow1s="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20220713155537-f223a00ba0e2"
    hash = "sha256-hWhSoc0Y7YbWfUbesf0tOgEPK61F/tNQo2zN6RcYgro="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.2.3"
    hash = "sha256-v6u6ZqnrEeQ2c7BYkltPKuBFL7+939OT1EbWw0mUE7U="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.2.0"
    hash = "sha256-HHqIfaFuKGalif3bP2CcHm8MT8Ily1kJQL9Q8Kz2WHA="
